# Generated by Alembic
from alembic import op
import sqlalchemy as sa


def upgrade():
    op.create_unique_constraint(
        'unique_chatbot_name',  # Name for the constraint
        'chatbots',  # The table name
        ['name']  # The column name(s) to apply the constraint to
    )


def downgrade():
    op.drop_constraint('unique_chatbot_name', 'chatbots', type_='unique')
